# Generated by Django 6.0.7 on 2026-08-30 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('planted_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planted', 'Planted'), ('growing', 'Growing'), ('harvested', 'Harvested'), ('failed', 'Failed')], default='planted', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='farms.farm')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
