# Generated by Django 6.0.7 on 2026-08-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Raw model class name, e.g. "Tomato___Late_blight".', max_length=255, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('plant', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('symptoms', models.TextField(blank=True)),
                ('treatment', models.TextField(blank=True)),
                ('prevention', models.TextField(blank=True)),
                ('is_healthy', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['plant', 'display_name'],
            },
        ),
    ]
