# Generated by Django 6.0.7 on 2026-08-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('temperature', models.FloatField(help_text='Temperature in Celsius.')),
                ('humidity', models.FloatField(blank=True, help_text='Relative humidity in percent.', null=True)),
                ('rainfall', models.FloatField(blank=True, help_text='Rainfall in millimeters.', null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
